[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
lazy_static = "1.4.0"
log = "0.4.21"
thiserror = "1.0.59"

[[bench]]
name = "move_gen"
harness = false
